# Generated by Django 4.2.30 on 2026-06-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nid_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
