# Generated by Django 4.2.30 on 2026-06-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0003_user_nid_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicianprofile',
            name='availability_status',
            field=models.BooleanField(default=False),
        ),
    ]
