# Generated by Django 4.2.30 on 2026-06-13 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_status_ticketmessage_review_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketMessage',
        ),
    ]
