# Generated by Django 4.2.30 on 2026-06-13 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_delete_ticketmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
