# Generated by Django 4.2.30 on 2026-06-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
